### ISSUE TITLE
Dependency doesn't install

### ISSUE THREAD

**Issue by felixsanz** [tangledfruit/rx-couch#27]
npm install --save rx-couch

├── UNMET PEER DEPENDENCY rx@>=4.0.7 <5
└─┬ rx-couch@1.5.1 
  ├─┬ deep-eql@0.1.3 
  │ └── type-detect@0.1.1 
  ├── deepmerge@0.2.10 
  ├── UNMET PEER DEPENDENCY rx@>=4.0.7 <5
  ├─┬ rx-fetch@1.2.0 
  │ └─┬ isomorphic-fetch@2.2.1 
  │   ├─┬ node-fetch@1.3.3 
  │   │ └─┬ encoding@0.1.12 
  │   │   └── iconv-lite@0.4.13 
  │   └── whatwg-fetch@0.11.0 
  └── shallow-copy@0.0.1 

As a result

```
Error: Cannot find module 'rx'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
```

**Comment by tangledfruit** [comment]
Hi Felix, if I add rx as a normal dependency, I run into a race condition with multiple copies of rx being installed by npm 2.x. This wouldn't necessarily be an issue for end users of rx-couch, but it makes testing more difficult.

You'll need to add rx as an explicit dependency of your project.

In #30 I've added a new error message to make that more obvious and also added some comments that should explain this to future users.

Thanks for pointing this out!

**Comment by felixsanz** [comment]
npm is actually 3.8.0, why still use 2.x ? Anyway, it's weird because rx-couch **IS** depending on rx. So it should be installed. I mean, the fix should be against the race condition, not by installing the package manually. Its just an idea and my $0.02.

Thanks!

**Comment by tangledfruit** [comment]
@felixsanz: Ah, now I see that I can use `{ "engines" : { "npm" : ">=3" } }` to discourage installation via npm 2.x. I'll push that through this and the other libraries. Should be an update soon.

The race condition is that – with multiple copies of rx running around – it's not clear which one gets patched by rx-to-async-iterator, so the tests (which rely on adding new features to rx) may or may not fail depending on which one gets installed first. npm 3 solves that race by flattening the modules tree and having only one copy of rx installed.

Requiring (or at least strongly encouraging) npm 3 seems like it might be a better fix.

**Comment by felixsanz** [comment]
but i use npm 3.8 and thats why i created this issue, because it doesn't work :stuck_out_tongue_closed_eyes:

**Comment by tangledfruit** [comment]
Agreed. With npm 3.x the race condition I was trying to avoid goes away and I can safely list rx as a regular dependency, which I will do shortly. I'm working my way up the dependency chain now. Should be live shortly.

**Comment by felixsanz** [comment]
Oh sorry, i had understood that you just add "npm" : ">=3"  and all solved. I was like .. uh? what? hah.

Thanks. Feel free to close the issue when you consider.

**Comment by tangledfruit** [comment]
Yeah, now discovering that Travis CI is failing the node 4.0 builds because it installs npm 2.something. Fun times.

**Comment by tangledfruit** [comment]
@felixsanz: Does this work for you? Please close if so.

**Comment by felixsanz** [comment]
It works now:

└─┬ rx-couch@1.5.3 
  ├─┬ deep-eql@0.1.3 
  │ └── type-detect@0.1.1 
  ├── deepmerge@0.2.10 
  ├── rx@4.0.8  <----------- :sunglasses: 
  ├─┬ rx-fetch@1.2.2 
  │ └─┬ isomorphic-fetch@2.2.1 
  │   ├─┬ node-fetch@1.3.3 
  │   │ └─┬ encoding@0.1.12 
  │   │   └── iconv-lite@0.4.13 
  │   └── whatwg-fetch@0.11.0 
  └── shallow-copy@0.0.1 

Thanks!

**Comment by tangledfruit** [comment]
Great news! LMK if you run into anything else.
