### ISSUE TITLE
server.createDatabase should produce an error if the db already exists

### ISSUE THREAD

**Issue by paddlefish** [tangledfruit/rx-couch#7]
... I wanted to do some testing where I would go ahead and delete the previous database if it already exists.  The most natural way, at least it seemed to me at the time, was to simply try to create it and if it fails then delete it and create it again.

E.g. if "test" already exists,

```
server.createDatabase("test") // => Should produce an error
```

**Comment by tangledfruit** [comment]
Fixed by #9.
