### ISSUE TITLE
Don't assert no / in server URL

### ISSUE THREAD

**Issue by paddlefish** [tangledfruit/rx-couch#73]
I've used nginx to forward some URLs to couchdb like this:

nginx default site configuration file

```
server {
        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;

        location /couch/ {
                proxy_pass  http://127.0.0.1:5984;
                proxy_set_header Host 127.0.0.1;
                proxy_redirect off;
                rewrite ^/couch/?(.*)$ /$1 break;
        }
}
```

This means I can host multiple services under one API, e.g. a node.js service at /api/ and couch at /couch/.  rx-couch creates an error if this is done, however, due to 

```
  if (pathName && pathName !== '/') {
    throw new Error('CouchDB server must not contain a path or query string');
  }
```

I think instead it should ensure that if the pathName is not empty, it should END with a '/'.  That way I can use, for example, couchDbHost=http://localhost/couch/ couchDbName=nextcouch and rx-couch works perfectly resolving URLs relative to /couch/

Actually now that i think about it, maybe just add the '/' if it is not empty and doesn't end with a '/'.  That way I could specify couchDbHost=http://localhost/couch and it would still work correctly.

**Comment by tangledfruit** [comment]
@paddlefish: Just published version 1.7.6 with this fix.
